# Generated by Django 4.0.3 on 2022-03-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALongitude', models.FloatField()),
                ('ALatitude', models.FloatField()),
                ('BLongitude', models.FloatField()),
                ('BLatitude', models.FloatField()),
                ('CLongitude', models.FloatField()),
                ('CLatitude', models.FloatField()),
                ('DLongitude', models.FloatField()),
                ('DLatitude', models.FloatField()),
                ('CO', models.FloatField()),
                ('O3', models.FloatField()),
                ('NO2', models.FloatField()),
                ('SO2', models.FloatField()),
                ('PM10', models.FloatField()),
                ('PM2_5', models.FloatField()),
                ('AQI', models.FloatField()),
            ],
        ),
    ]
