# Generated by Django 4.0.3 on 2022-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('Longtitudes', models.FloatField()),
                ('Latitudes', models.FloatField()),
                ('CO', models.FloatField()),
                ('O3', models.FloatField()),
                ('NO2', models.FloatField()),
                ('SO2', models.FloatField()),
                ('PM10', models.FloatField()),
                ('PM2_5', models.FloatField()),
                ('AQI', models.FloatField()),
            ],
        ),
    ]
