# Generated by Django 4.0.3 on 2022-03-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_pointvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvalues',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
