# Generated by Django 3.2.12 on 2022-03-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_pointvalues_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointValues',
        ),
    ]
